version: '2'
services:
    ubuntu-build:
        image: gulinux/planetaryimager_build:ubuntu-16.04-64bit
        volumes:
            - ../../../:/code
            - ${DEST}:/dest
        command: >
          bash -c "cmake /code
          -DEXTRA_LIBRARIES=udev
          -DCMAKE_PREFIX_PATH=/opt/libusb-git
          -DCMAKE_INSTALL_PREFIX=/usr
          -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
          -DCPACK_GENERATOR=TBZ2
          -DPACKAGE_VERSION_SUFFIX=-${DAILY_TAG}
          -DCPACK_PACKAGE_DIRECTORY=/dest
          -DVERSION_SUFFIX=-${DAILY_TAG_SUFFIX}
          ${CMAKE_EXTRA_OPTIONS} &&
          make ${MAKE_OPTS} && make package"
