version: '2'
services:
    ubuntu-build:
        build:
          context: .
          args:
            - http_proxy
            - https_proxy
        image: planetaryimager-ubuntu:16.04
        volumes:
            - ../../../:/code
            - ${DEST}:/dest
        command: "bash -c \"cmake /code -DEXTRA_LIBRARIES=udev -DCMAKE_PREFIX_PATH=/opt/libusb-git -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ${CMAKE_EXTRA_OPTIONS} && make ${MAKE_OPTS} && make package && rename.ul Linux  Ubuntu-16.04-x86_64 /build/*.deb && cp /build/PlanetaryImager-*.deb /dest/ \""


