version: '2'
services:
    ubuntu-build:
        build:
          context: .
          args:
            - http_proxy
            - https_proxy
        image: planetaryimager-ubuntu:16.04-raspberry
        volumes:
            - ../../../:/code
            - ${DEST}:/dest
        command: >
          bash -c "cmake /code
          -DEXTRA_LIBRARIES=udev
          -DCMAKE_PREFIX_PATH=/opt/libusb-git
          -DCMAKE_INSTALL_PREFIX=/usr
          -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
          -DCPACK_GENERATOR=DEB
          -DPACKAGE_NAME_SUFFIX=_ubuntu-xenial
          -DCPACK_PACKAGE_DIRECTORY=/dest
          ${CMAKE_EXTRA_OPTIONS} &&
          make ${MAKE_OPTS} && make package"


